/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ControlPlaneFilterParametersClusterType {
    StringFieldEqualsFilter(Box<models::StringFieldEqualsFilter>),
    StringFieldNeqFilter(Box<models::StringFieldNeqFilter>),
}

impl Default for ControlPlaneFilterParametersClusterType {
    fn default() -> Self {
        Self::StringFieldEqualsFilter(Default::default())
    }
}

