/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ControlPlaneFilterParameters {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<models::ControlPlaneFilterParametersId>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::ControlPlaneFilterParametersName>>,
    #[serde(rename = "cluster_type", skip_serializing_if = "Option::is_none")]
    pub cluster_type: Option<Box<models::ControlPlaneFilterParametersClusterType>>,
    /// Filter by a boolean value (true/false).
    #[serde(rename = "cloud_gateway", skip_serializing_if = "Option::is_none")]
    pub cloud_gateway: Option<bool>,
}

impl ControlPlaneFilterParameters {
    pub fn new() -> ControlPlaneFilterParameters {
        ControlPlaneFilterParameters {
            id: None,
            name: None,
            cluster_type: None,
            cloud_gateway: None,
        }
    }
}

