/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CursorMetaWithSizeAndTotal {
    /// URI to the next page
    #[serde(rename = "next", deserialize_with = "Option::deserialize")]
    pub next: Option<String>,
    /// Requested page size
    #[serde(rename = "size")]
    pub size: f64,
    /// Total number of objects in the collection; will only be present on the first page
    #[serde(rename = "total", deserialize_with = "Option::deserialize")]
    pub total: Option<f64>,
}

impl CursorMetaWithSizeAndTotal {
    pub fn new(next: Option<String>, size: f64, total: Option<f64>) -> CursorMetaWithSizeAndTotal {
        CursorMetaWithSizeAndTotal {
            next,
            size,
            total,
        }
    }
}

