/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CursorPaginatedMetaWithSizeAndTotal : returns the pagination information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CursorPaginatedMetaWithSizeAndTotal {
    #[serde(rename = "page")]
    pub page: Box<models::CursorMetaWithSizeAndTotal>,
}

impl CursorPaginatedMetaWithSizeAndTotal {
    /// returns the pagination information
    pub fn new(page: models::CursorMetaWithSizeAndTotal) -> CursorPaginatedMetaWithSizeAndTotal {
        CursorPaginatedMetaWithSizeAndTotal {
            page: Box::new(page),
        }
    }
}

