/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetControlPlanesIdGroupMemberships200Response {
    #[serde(rename = "meta")]
    pub meta: Box<models::CursorPaginatedMetaWithSizeAndTotal>,
    /// Array of control planes summary who are a child to this control plane group.
    #[serde(rename = "data")]
    pub data: Vec<models::ControlPlane>,
}

impl GetControlPlanesIdGroupMemberships200Response {
    pub fn new(meta: models::CursorPaginatedMetaWithSizeAndTotal, data: Vec<models::ControlPlane>) -> GetControlPlanesIdGroupMemberships200Response {
        GetControlPlanesIdGroupMemberships200Response {
            meta: Box::new(meta),
            data,
        }
    }
}

