/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetControlPlanesIdGroupStatus200Response {
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::GroupStatus>>,
}

impl GetControlPlanesIdGroupStatus200Response {
    pub fn new() -> GetControlPlanesIdGroupStatus200Response {
        GetControlPlanesIdGroupStatus200Response {
            item: None,
        }
    }
}

