/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupConflictResource : A resource causing a conflict in a control plane group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupConflictResource {
    /// The ID of the resource.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The type of the resource.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl GroupConflictResource {
    /// A resource causing a conflict in a control plane group.
    pub fn new(id: uuid::Uuid, r#type: String) -> GroupConflictResource {
        GroupConflictResource {
            id,
            r#type,
        }
    }
}

