/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupConflict : The Group Conflict object contains information about a conflict in a control plane group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupConflict {
    /// The ID of a control plane member of a control plane group.
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    /// The description of the conflict.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "resource")]
    pub resource: Box<models::GroupConflictResource>,
}

impl GroupConflict {
    /// The Group Conflict object contains information about a conflict in a control plane group.
    pub fn new(cluster_id: uuid::Uuid, description: String, resource: models::GroupConflictResource) -> GroupConflict {
        GroupConflict {
            cluster_id,
            description,
            resource: Box::new(resource),
        }
    }
}

