/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupMemberStatus : Object with information determining the group membership status of a control plane.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupMemberStatus {
    /// Boolean indicating if a control plane is a member of a control plane group.
    #[serde(rename = "is_member")]
    pub is_member: bool,
}

impl GroupMemberStatus {
    /// Object with information determining the group membership status of a control plane.
    pub fn new(is_member: bool) -> GroupMemberStatus {
        GroupMemberStatus {
            is_member,
        }
    }
}

