/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupMembershipMembersInner {
    #[serde(rename = "id")]
    pub id: String,
}

impl GroupMembershipMembersInner {
    pub fn new(id: String) -> GroupMembershipMembersInner {
        GroupMembershipMembersInner {
            id,
        }
    }
}

