/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidParameterDependentItem {
    #[serde(rename = "field")]
    pub field: String,
    /// invalid parameters rules
    #[serde(rename = "rule", deserialize_with = "Option::deserialize")]
    pub rule: Option<Rule>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "dependents", deserialize_with = "Option::deserialize")]
    pub dependents: Option<Vec<serde_json::Value>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl InvalidParameterDependentItem {
    pub fn new(field: String, rule: Option<Rule>, reason: String, dependents: Option<Vec<serde_json::Value>>) -> InvalidParameterDependentItem {
        InvalidParameterDependentItem {
            field,
            rule,
            reason,
            dependents,
            source: None,
        }
    }
}
/// invalid parameters rules
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rule {
    #[serde(rename = "dependent_fields")]
    DependentFields,
}

impl Default for Rule {
    fn default() -> Rule {
        Self::DependentFields
    }
}

