/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidParameterMaximumLength {
    #[serde(rename = "field")]
    pub field: String,
    /// invalid parameters rules
    #[serde(rename = "rule")]
    pub rule: Rule,
    #[serde(rename = "maximum")]
    pub maximum: i32,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl InvalidParameterMaximumLength {
    pub fn new(field: String, rule: Rule, maximum: i32, reason: String) -> InvalidParameterMaximumLength {
        InvalidParameterMaximumLength {
            field,
            rule,
            maximum,
            source: None,
            reason,
        }
    }
}
/// invalid parameters rules
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rule {
    #[serde(rename = "max_length")]
    MaxLength,
    #[serde(rename = "max_items")]
    MaxItems,
    #[serde(rename = "max")]
    Max,
}

impl Default for Rule {
    fn default() -> Rule {
        Self::MaxLength
    }
}

