/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvalidParametersInner {
    InvalidParameterStandard(Box<models::InvalidParameterStandard>),
    InvalidParameterMinimumLength(Box<models::InvalidParameterMinimumLength>),
    InvalidParameterMaximumLength(Box<models::InvalidParameterMaximumLength>),
    InvalidParameterChoiceItem(Box<models::InvalidParameterChoiceItem>),
    InvalidParameterDependentItem(Box<models::InvalidParameterDependentItem>),
}

impl Default for InvalidParametersInner {
    fn default() -> Self {
        Self::InvalidParameterStandard(Default::default())
    }
}
/// invalid parameters rules
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rule {
    #[serde(rename = "dependent_fields")]
    DependentFields,
}

impl Default for Rule {
    fn default() -> Rule {
        Self::DependentFields
    }
}

