/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidParameterStandard {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "rule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rule: Option<Option<models::InvalidRules>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl InvalidParameterStandard {
    pub fn new(field: String, reason: String) -> InvalidParameterStandard {
        InvalidParameterStandard {
            field,
            rule: None,
            source: None,
            reason,
        }
    }
}

