/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidParameterMinimumLength {
    #[serde(rename = "field")]
    pub field: String,
    /// invalid parameters rules
    #[serde(rename = "rule")]
    pub rule: Rule,
    #[serde(rename = "minimum")]
    pub minimum: i32,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl InvalidParameterMinimumLength {
    pub fn new(field: String, rule: Rule, minimum: i32, reason: String) -> InvalidParameterMinimumLength {
        InvalidParameterMinimumLength {
            field,
            rule,
            minimum,
            source: None,
            reason,
        }
    }
}
/// invalid parameters rules
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rule {
    #[serde(rename = "min_length")]
    MinLength,
    #[serde(rename = "min_digits")]
    MinDigits,
    #[serde(rename = "min_lowercase")]
    MinLowercase,
    #[serde(rename = "min_uppercase")]
    MinUppercase,
    #[serde(rename = "min_symbols")]
    MinSymbols,
    #[serde(rename = "min_items")]
    MinItems,
    #[serde(rename = "min")]
    Min,
}

impl Default for Rule {
    fn default() -> Rule {
        Self::MinLength
    }
}

