/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListControlPlanesResponse {
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginatedMeta>,
    #[serde(rename = "data")]
    pub data: Vec<models::ControlPlane>,
}

impl ListControlPlanesResponse {
    pub fn new(meta: models::PaginatedMeta, data: Vec<models::ControlPlane>) -> ListControlPlanesResponse {
        ListControlPlanesResponse {
            meta: Box::new(meta),
            data,
        }
    }
}

