/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageMeta : Contains pagination query parameters and the total number of objects returned.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageMeta {
    #[serde(rename = "number")]
    pub number: f64,
    #[serde(rename = "size")]
    pub size: f64,
    #[serde(rename = "total")]
    pub total: f64,
}

impl PageMeta {
    /// Contains pagination query parameters and the total number of objects returned.
    pub fn new(number: f64, size: f64, total: f64) -> PageMeta {
        PageMeta {
            number,
            size,
            total,
        }
    }
}

