/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProxyUrl : Proxy URL associated with reaching the data-planes connected to a control-plane.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProxyUrl {
    /// Hostname of the proxy URL.
    #[serde(rename = "host")]
    pub host: String,
    /// Port of the proxy URL.
    #[serde(rename = "port")]
    pub port: i32,
    /// Protocol of the proxy URL.
    #[serde(rename = "protocol")]
    pub protocol: String,
}

impl ProxyUrl {
    /// Proxy URL associated with reaching the data-planes connected to a control-plane.
    pub fn new(host: String, port: i32, protocol: String) -> ProxyUrl {
        ProxyUrl {
            host,
            port,
            protocol,
        }
    }
}

