/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceUnavailableError : Error response for temporary service unavailability.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceUnavailableError {
    /// The HTTP status code.
    #[serde(rename = "status")]
    pub status: Status,
    /// The error response code.
    #[serde(rename = "title")]
    pub title: String,
    /// The Konnect traceback code
    #[serde(rename = "instance")]
    pub instance: String,
    /// Details about the error.
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl ServiceUnavailableError {
    /// Error response for temporary service unavailability.
    pub fn new(status: Status, title: String, instance: String) -> ServiceUnavailableError {
        ServiceUnavailableError {
            status,
            title,
            instance,
            detail: None,
        }
    }
}
/// The HTTP status code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "503")]
    Variant503,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant503
    }
}

