/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StringFieldEqualsFilter : Filters on the given string field value by exact match.
/// Filters on the given string field value by exact match.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StringFieldEqualsFilter {
    String(String),
    StringFieldEqualsComparison(Box<models::StringFieldEqualsComparison>),
}

impl Default for StringFieldEqualsFilter {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

