/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StringFieldOeqFilter : Returns entities that exact match any of the comma-delimited phrases in the filter string.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StringFieldOeqFilter {
    #[serde(rename = "oeq")]
    pub oeq: String,
}

impl StringFieldOeqFilter {
    /// Returns entities that exact match any of the comma-delimited phrases in the filter string.
    pub fn new(oeq: String) -> StringFieldOeqFilter {
        StringFieldOeqFilter {
            oeq,
        }
    }
}

