/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StringFieldNeqFilter : Filters on the given string field value by exact match inequality.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StringFieldNeqFilter {
    #[serde(rename = "neq")]
    pub neq: String,
}

impl StringFieldNeqFilter {
    /// Filters on the given string field value by exact match inequality.
    pub fn new(neq: String) -> StringFieldNeqFilter {
        StringFieldNeqFilter {
            neq,
        }
    }
}

