/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StringFieldContainsFilter : Filters on the given string field value by fuzzy match.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StringFieldContainsFilter {
    #[serde(rename = "contains")]
    pub contains: String,
}

impl StringFieldContainsFilter {
    /// Filters on the given string field value by fuzzy match.
    pub fn new(contains: String) -> StringFieldContainsFilter {
        StringFieldContainsFilter {
            contains,
        }
    }
}

