/*
 * Konnect Control Planes
 *
 * The API for Kong Konnect Control Planes.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateControlPlaneRequest : The request schema for the update control plane request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateControlPlaneRequest {
    /// The name of the control plane.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of the control plane in Konnect.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The auth type value of the cluster associated with the Runtime Group.
    #[serde(rename = "auth_type", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<AuthType>,
    /// Array of proxy URLs associated with reaching the data-planes connected to a control-plane.
    #[serde(rename = "proxy_urls", skip_serializing_if = "Option::is_none")]
    pub proxy_urls: Option<Vec<models::ProxyUrl>>,
    /// Labels to facilitate tagged search on control planes. Keys must be of length 1-63 characters, and cannot start with 'kong', 'konnect', 'mesh', 'kic', or '_'.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
}

impl UpdateControlPlaneRequest {
    /// The request schema for the update control plane request.
    pub fn new() -> UpdateControlPlaneRequest {
        UpdateControlPlaneRequest {
            name: None,
            description: None,
            auth_type: None,
            proxy_urls: None,
            labels: None,
        }
    }
}
/// The auth type value of the cluster associated with the Runtime Group.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthType {
    #[serde(rename = "pinned_client_certs")]
    PinnedClientCerts,
    #[serde(rename = "pki_client_certs")]
    PkiClientCerts,
}

impl Default for AuthType {
    fn default() -> AuthType {
        Self::PinnedClientCerts
    }
}

