[package]
name = "error_handling"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
openapi = { path = "./api" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
