[package]
name = "collector"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = { version = "0.34.2", features = ["apple-app-store", "windows"] }
shared_data = { path = "../shared_data" }
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["fast-rng", "v4"] }
